/**
 * GENERATED by scripts/generate-playbook-assets.mjs — do not edit.
 *
 * Intrinsic dimensions of every playbook image, so each one can reserve its
 * own box. Regenerate after adding or replacing a master.
 */
export const playbookImages = {
  "snapshots": {
    "contents": {
      "width": 1132,
      "height": 817
    },
    "module-page": {
      "width": 1057,
      "height": 657
    },
    "scorecard": {
      "width": 1067,
      "height": 567
    },
    "tracker-excel": {
      "width": 1917,
      "height": 937
    },
    "pipeline": {
      "width": 845,
      "height": 842
    },
    "swipe-file": {
      "width": 1057,
      "height": 905
    },
    "never-say": {
      "width": 1052,
      "height": 866
    },
    "prompt-pack": {
      "width": 1047,
      "height": 907
    },
    "regulated": {
      "width": 1027,
      "height": 587
    },
    "plan": {
      "width": 1052,
      "height": 907
    },
    "plan-week": {
      "width": 1102,
      "height": 881
    },
    "invoice": {
      "width": 1770,
      "height": 712
    },
    "site-cafe": {
      "width": 1890,
      "height": 908
    },
    "bundle-files": {
      "width": 1082,
      "height": 517
    },
    "module-files": {
      "width": 942,
      "height": 402
    }
  },
  "proofs": {
    "reply-1": {
      "width": 386,
      "height": 637
    },
    "reply-2": {
      "width": 382,
      "height": 586
    },
    "reply-3": {
      "width": 380,
      "height": 587
    },
    "reply-4": {
      "width": 381,
      "height": 607
    }
  }
} as const;

export type PlaybookImageKind = keyof typeof playbookImages;
