/**
 * Writes out/_headers: the site's HTTP security headers, including a strict,
 * hash-based Content-Security-Policy.
 *
 * Runs automatically after `npm run build` (the `postbuild` script), so the
 * policy is always computed from the HTML that is actually being deployed.
 *
 * WHY HASHES
 * Next.js bootstraps every page with inline <script> tags. The usual way to
 * allow them is a per-request nonce, which needs a server; this site is a
 * static export with no server. The alternative, `'unsafe-inline'`, allows ANY
 * inline script — including one an attacker managed to inject — and makes the
 * CSP close to decorative. So instead every inline script in the build is
 * hashed and only those exact scripts may run. Anything else inline is blocked.
 *
 * `'unsafe-inline'` IS kept for styles: React renders `style` attributes for
 * animation delays and positions, and CSS injection is a far smaller risk than
 * script injection.
 *
 * WIRING UP THE CONTACT FORM
 * If submitContact() posts to another origin (Formspree, Resend, ...), add that
 * origin to CONNECT_SRC below or the browser will refuse the request. A
 * same-origin Netlify Function needs no change.
 *
 * Netlify reads `_headers` from the publish directory and merges it with any
 * [[headers]] in netlify.toml. Keep every header in exactly one of the two:
 * Netlify joins duplicate header names, and two CSPs are both enforced.
 */
import { createHash } from "node:crypto";
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = join(dirname(fileURLToPath(import.meta.url)), "..", "out");

/** Extra origins the contact form may post to. Empty while it is a stub. */
const CONNECT_SRC = [];

function htmlFiles(dir) {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const path = join(dir, entry.name);
    if (entry.isDirectory()) return htmlFiles(path);
    return entry.name.endsWith(".html") ? [path] : [];
  });
}

// Inline, executable scripts only. External scripts are covered by 'self',
// and JSON-LD blocks are data — CSP does not apply to them.
const INLINE_SCRIPT = /<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/g;

const NL = String.fromCharCode(10);

const pages = htmlFiles(OUT);
if (pages.length === 0) {
  throw new Error("security-headers: no HTML found in out/ — did the build run?");
}

function scriptHashes(file) {
  const hashes = new Set();
  const html = readFileSync(file, "utf8");
  for (const [, attributes, body] of html.matchAll(INLINE_SCRIPT)) {
    if (/type=["']?application\/(ld\+)?json/.test(attributes)) continue;
    hashes.add(`'sha256-${createHash("sha256").update(body, "utf8").digest("base64")}'`);
  }
  return [...hashes].sort();
}

function csp(hashes) {
  return [
    "default-src 'self'",
    `script-src 'self' ${hashes.join(" ")}`,
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data:",
    "font-src 'self'",
    `connect-src ${["'self'", ...CONNECT_SRC].join(" ")}`,
    "media-src 'self'",
    "manifest-src 'self'",
    "worker-src 'none'",
    "frame-src 'none'",
    "object-src 'none'",
    "base-uri 'none'",
    "form-action 'self'",
    "frame-ancestors 'none'",
    "upgrade-insecure-requests",
  ].join("; ");
}

/**
 * PER-PAGE POLICIES
 * One site-wide policy listing every page's hashes grew by ~250 bytes per
 * page (7.5 KB at 30 pages) — heading for proxy header limits, and it let any
 * page run any other page's bootstrap scripts. Each page now gets only its own
 * hashes, on its exact path.
 *
 * The CSP is deliberately NOT on `/*`: Netlify combines every matching rule,
 * and two Content-Security-Policy headers are both enforced, so a wildcard
 * policy would block every page's scripts. Paths with no page of their own
 * (served the 404 page) get the other security headers but no CSP.
 */
function routesFor(file) {
  const rel = relative(OUT, file).split(sep).join("/");
  if (rel === "index.html") return ["/"];
  if (!rel.endsWith("/index.html")) return []; // 404.html and other flat files
  const dir = rel.slice(0, -"/index.html".length);
  if (dir === "404" || dir === "_not-found") return [];
  return [`/${dir}/`, `/${dir}`];
}

const pageRules = pages
  .flatMap((file) => {
    const routes = routesFor(file);
    if (routes.length === 0) return [];
    const policy = csp(scriptHashes(file));
    return routes.map((route) => [route, `  Content-Security-Policy: ${policy}`].join(NL));
  })
  .sort();

const largest = Math.max(...pageRules.map((rule) => rule.length));

const headers = `# GENERATED by scripts/security-headers.mjs on every build — do not edit.

/*
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  X-Frame-Options: DENY
  Referrer-Policy: strict-origin-when-cross-origin
  Permissions-Policy: accelerometer=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=()
  Cross-Origin-Opener-Policy: same-origin
  Cross-Origin-Resource-Policy: same-origin
  Origin-Agent-Cluster: ?1

# Content-hashed build output never changes under the same URL.
/_next/static/*
  Cache-Control: public, max-age=31536000, immutable

# Per-page Content-Security-Policy.
${pageRules.join(NL + NL)}
`;

writeFileSync(join(OUT, "_headers"), headers);
console.log(
  `security-headers: ${pageRules.length} page policies from ${pages.length} HTML files -> out/_headers (largest policy ${largest} bytes)`,
);
